# Generated by Django 3.2.4 on 2021-07-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComWebsiteApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='phn_number',
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
